
variables:
    APP_NAME: "serviceapp_laravel_backend"
    DOCKER_REGISTRY: docker.photonicdata.science
    http_proxy: ${CI_PROXY}
    https_proxy: ${CIS_PROXY}
    no_proxy: ${DOCKER_REGISTRY}
    TAG: "v0.1.0"

image:
  name: gcr.io/kaniko-project/executor:v1.7.0-debug
  entrypoint: [""]
stages:
  - build
  - redeploy
before_script:
  - TAG=$(cat version.txt)
build-and-push:  
  stage: build
  before_script:
    - TAG=$(cat version.txt)
  only:
    - master
    - staging
  script:
    - mkdir -p /kaniko/.docker
    - |-
       KANIKOPROXYBUILDARGS=""
       KANIKOCFG="\"auths\":{\"${DOCKER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USER}" "${DOCKER_PASS}" | base64 | tr -d '\n')\"}}"
       if [ "x${http_proxy}" != "x" -o "x${https_proxy}" != "x" ]; then
         KANIKOCFG="${KANIKOCFG}, \"proxies\": { \"default\": { \"httpProxy\": \"${http_proxy}\", \"httpsProxy\": \"${https_proxy}, \"noProxy\": \"${no_proxy}\"}\"}}"
         KANIKOPROXYBUILDARGS="--build-arg=\"http_proxy=${http_proxy}\" --build-arg=\"https_proxy=${https_proxy}\" --build-arg=\"no_proxy=${no_proxy}\""
       fi
       KANIKOCFG="{ ${KANIKOCFG} }"
       echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_REGISTRY}/${APP_NAME}:${CI_COMMIT_TAG}"
      --destination "${DOCKER_REGISTRY}/${APP_NAME}:${TAG}"
      --destination "${DOCKER_REGISTRY}/${APP_NAME}:latest"
      "${KANIKOPROXYBUILDARGS}"
rancher-redeploy:
  image: debian:latest
  only:
    - master
    - staging
  variables:
    RUNMODE: "other"
  stage: redeploy
  script:
    - apt update
    - apt install curl -y
    - curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    - chmod +x /usr/local/bin/argocd
    - argocd app set serviceapp-laravel -p image.tag=${TAG} --server ${ARGOCD_SERVER} --auth-token ${ARGOCD_TOKEN}
