image: docker:stable
services:
  - docker:dind
variables:
  DOCKER_USERNAME: "docker.photonicdata.science"
  NAME: "vibspecdb_laravel_backend"
  TAG: "v0.1.0"
stages:
  - build
  - push
  - redeploy
before_script:
  - TAG=$(cat version.txt)
build-image:
  stage: build
  # rules:
    # - if: ($CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'staging') && $CI_COMMIT_TAG != null
  script: 
   - echo $CI_COMMIT_BRANCH
   - echo $CI_COMMIT_TAG
  #  - docker build --tag ${DOCKER_USERNAME}/${NAME}:${TAG} . 
.docker-registry-auth:
  stage: push
  rules:
    - if: ($CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'staging') && $CI_COMMIT_TAG != null
  script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_U -p $DOCKER_P
    - docker push ${DOCKER_USERNAME}/${NAME}:${TAG}
.rancher-redeploy:
  variables:
    RUNMODE: "other"
  stage: redeploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      variables: 
        RUNMODE: " "
    - if: $CI_COMMIT_BRANCH == 'staging'
      variables: 
        RUNMODE: "-staging"
  script: 
    - echo 'todos here'
