version: '3'
services:
    pgsql:
        image: 'postgres:13'
        container_name: vb-pgsql
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'vb-sailpgsql:/var/lib/postgresql/data'
        networks:
            - vb-laravel-php
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: vb-redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - vb-laravel-php
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    argo.fastapi:
        profiles:
            - donotstart   
        container_name: vb-argo_fastapi
        build:
            context: ../fastapi-argo
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - '../fastapi-argo:/code'
        networks:
            - vb-laravel-php           
    laravel.dev:
        container_name: vb-laravel_sail
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 1000M
                reservations:
                    cpus: '1'
                    memory: 800M
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: ${SAIL_DEBUG}
        image: sail-8.1/app
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            # XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            # XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            # - ./vendor:/var/www/html/vendor
        networks:
            - vb-laravel-php
        depends_on:
            - pgsql
            - redis            
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        container_name: vb-soketi
        environment:
            DEBUG: '1'
            METRICS_SERVER_PORT: '9601'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        networks: 
            - vb-laravel-php    
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: vb-mailhog
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
           - vb-laravel-php
    meilisearch:
        profiles:
            - donotstart
        container_name: vb-meilisearch
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'vb-sailmeilisearch:/data.ms'
        networks:
            - vb-laravel-php
        healthcheck:
          test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
          retries: 3
          timeout: 5s
    minio:
        image: 'minio/minio:latest'
        container_name: vb-minio
        ports:
            - '${MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_PORT:-9001}:9001'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
            MINIO_STORAGE_USE_HTTPS: false
        volumes:
            - 'vb-minio:/data'
        networks:
            -  vb-laravel-php
        command: ["server", "--console-address", ":9001","/data"]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3          
volumes:
    vb-sailvendor:
        driver: local
    vb-sailpgsql:
        driver: local
        # driver_opts:
        #     o: "size=500m,uid=1000"
    vb-minio:
        driver: local
        # driver_opts:
        #     o: "size=5000m,uid=1000"
    vb-sailmeilisearch:
        driver: local

# Create a bridged network to be used by containers.
# This will allow us to easily target other containers in the same stack
networks:
    vb-laravel-php:
        driver: bridge
