export const metatypes = {
  batch: 'Batch',
  date: 'Date',
  date_device: 'Date Device',
  device: 'Device',
  filename: 'Filename',
  metadata_source: 'Metadata Source',
  origin: 'Origin',
  path: 'Path',
  species: 'Species',
  dark_bg: 'Dark Bg',
  strain: 'Strain',
  top: 'Top',
  type: 'Type',
  interferent_sample: 'Interferent Sample',
  reference_sample: 'Reference Sample',
  standard: 'Standard',
  standard_intensity: 'Standard Intensity',
}
