#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# fix PHP formatting
./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --allow-risky=yes
npm run lint

# update (patch + 1) App version
php artisan version:patch

# save App version to the file
CURRENTV="$(php artisan version:show --format=version-only --suppress-app-name)"
echo $CURRENTV > version.txt

# add all changes to the git
git add .